### ISSUE TITLE
对于合并后的css文件的拆分功能

### ISSUE THREAD

**Issue by yacheng** [shepherdwind/plum#10]
#### 需求描述

一个线上页面的css引用往往是打包后的比如page.css
（这里是没有用less的情况）
其实在线下开发是开发多个模块文件，比如a.css、b.css、c.css
在上线前把这三个文件打包成page.css
用ucool调试时可以写一个combo.properties，文件内的文本格式如下

```
{baseUrl}/apps/someapp/release/20121129/inits/page.css={baseUrl}/apps/someapp/??mods/a.css,mods/b.css,mods/c.css
```

这样我在使用ucool代理时就可以代理道三个模块的css文件
调试时我修改一下a.css，虽然页面引用的page.css，刷新后我的修改是实时看得到的
#### 建议

希望拆解css的配置文件名和文本格式和ucool保持一直，这样两边可以通用

**Comment by shepherdwind** [comment]
baseUrl这个是什么，哪里来的，combo.properties这个文件放在什么位置？我从哪里去取

**Comment by yacheng** [comment]
baseUrl是线上或daily的地址，比如http://a.tbcdn.cn/
combo.properties在ucool的规则是放在代理服务器的根目录，希望plum能够支持放在应用的根目录，这样用起来方便而且跟着应用走

**Comment by shepherdwind** [comment]
在server下配置customs.combo，如下:

```
  "a.tbcdn.cn": {
      "customs": {
        "proxy": "",
        "combo": "/Users/eward/test/combo.properties"
      }
  }
```
